dict = {}
def morse(dict):
    dict["a"] = ".-"
    dict["b"] = "-..."
    dict["c"] = "-.-."
    dict["d"] = "-.."
    dict["e"] = "."
    dict["f"] = "..-."
    dict["g"] = "--."
    dict["h"] = "...."
    dict["i"] = ".."
    dict["j"] = ".---"
    dict["k"] = "-.-"
    dict["l"] = ".-.."
    dict["m"] = "--"
    dict["n"] = "-."
    dict["o"] = "---"
    dict["p"] = ".--."
    dict["q"] = "--.-"
    dict["r"] =".-."
    dict["s"] = "..."
    dict["t"] = "-"
    dict["u"] = "..-"
    dict["v"] = "...-"
    dict["w"] = ".--"
    dict["x"] = "-..-"
    dict["y"] = "-.--"
    dict["z"] = "--.."
    dict["0"] = "-----"
    dict["1"] = ".----"
    dict["2"] = "..---"
    dict["3"] = "...--"
    dict["4"] = "....-"
    dict["5"] = "....."
    dict["6"] = "-...."
    dict["7"] = "--..."
    dict["8"] = "---.."
    dict["9"] = "----."
    
    dict[" "] = " "
    dict["."] = ".-.-.-"
    dict[","] = "--..--"
    dict[":"] = "---..."
    dict["?"] = "..--.."
    dict["'"] = ".----."
    dict["!"] = "-.-.--"
    dict["/"] = "-..-."
    dict["("] = "-.--."
    dict[")"] = "-.--.-"
    dict["&"] = ".-..."
    dict[";"] = "-.-.-."
    dict["="] = "-...-"
    dict["+"] = ".-.-."
    dict["-"] = "-....-"
    dict["-"] = "..--.-"
    dict["$"] = "...-..-"
    dict["@"] = ".--.-."
    dict['"'] = ".-..-."

def alphabet(dict):
    dict[".-"] = "a"
    dict["-..."] = "b"
    dict["-.-."] = "c"
    dict["-.."] = "d"
    dict["."] = "e"
    dict["..-."] = "f"
    dict["--."] = "g"
    dict["...."] = "h"
    dict[".."] = "i"
    dict[".---"] = "j"
    dict["-.-"] = "k"
    dict[".-.."] = "l"
    dict["--"] = "m"
    dict["-."] = "n"
    dict[""] = "o"
    dict[""] = "p"
    dict[""] = "q"
    dict[""] = "r"
    dict[""] = "s"
    dict[""] = "t"
    dict[""] = "u"
    dict[""] = "v"
    dict[""] = "w"
    dict[""] = "x"
    dict[""] = "y"
    dict[""] = "z"

    dict[""] = "0"
    dict[""] = "1"
    dict[""] = "2"
    dict[""] = "3"
    dict[""] = "4"
    dict[""] = "5"
    dict[""] = "6"
    dict[""] = "7"
    dict[""] = "8"
    dict[""] = "9"

    dict[" "] = " "
    dict[".-.-.-"] = "."
    dict["--..--"] = ","
    dict["---..."] = ":"
    dict["?"] = "..--.."
    dict["'"] = ".----."
    dict["!"] = "-.-.--"
    dict["/"] = "-..-."
    dict["("] = "-.--."
    dict[")"] = "-.--.-"
    dict["&"] = ".-..."
    dict[";"] = "-.-.-."
    dict["="] = "-...-"
    dict["+"] = ".-.-."
    dict["-"] = "-....-"
    dict["-"] = "..--.-"
    dict["$"] = "...-..-"
    dict["@"] = ".--.-."
    dict['"'] = ".-..-."

texte = input("Écrivez votre texte :")
texte = texte.lower()
traduction = ""
morse(dict)
for lettre  in texte:
    trad = dict[lettre]
    traduction = traduction + trad + "/"
print(traduction)




